from __future__ import annotations

from backend.core.component_context import ComponentContext


class ContextBuilder:
    """
    Build the prompt messages for a single Component execution.
    """

    @staticmethod
    def build(
        context: ComponentContext,
        system_prompt: str,
    ) -> list[dict[str, str]]:

        messages: list[dict[str, str]] = [
            {
                "role": "system",
                "content": system_prompt,
            }
        ]

        runtime = context.runtime
        node = context.node

        # ======================================================
        # Workflow Status
        # ======================================================

        messages.append(
            {
                "role": "system",
                "content": f"""
================ CURRENT WORKFLOW ================

Current Component

{node.component_id}

Objective

{node.objective}

Expected Output

{node.expected_output}

=================================================
""".strip(),
            }
        )

        # ======================================================
        # Dependency Artifacts
        # ======================================================

        dependency_blocks: list[str] = []

        for parent in runtime.workflow.parents(
            node.id,
        ):

            artifact = runtime.get_artifact(
                parent.id,
            )

            if artifact is None:
                continue

            dependency_blocks.append(
                f"""
Component

{parent.component_id}

Artifact Type

{artifact.type}

Summary

{artifact.summary}
""".strip()
            )

        if dependency_blocks:

            messages.append(
                {
                    "role": "system",
                    "content": f"""
================ DEPENDENCY ARTIFACTS ================

The following artifacts were generated by previous components.

Use them as inputs.

Never regenerate them.

------------------------------------------------------

{chr(10).join(dependency_blocks)}

======================================================
""".strip(),
                }
            )

        # ======================================================
        # Component Inputs
        # ======================================================

        if context.inputs:

            input_blocks = []

            for key, value in context.inputs.items():

                input_blocks.append(
                    f"{key}\n\n{value}"
                )

            messages.append(
                {
                    "role": "system",
                    "content": f"""
================ COMPONENT INPUTS ================

{chr(10).join(input_blocks)}

==================================================
""".strip(),
                }
            )

        return messages